
GET localhost:3001/api/blogs

###
POST localhost:3001/api/blogs
Content-Type: application/json

{"title":"NewBlog","author":"Jon Johns","url":"www.example.com","likes":"1"}

###
POST localhost:3001/api/users
Content-Type: application/json

{}

###
GET localhost:3001/api/users


###
POST localhost:3001/api/users
Content-Type: application/json

{
    "username":"jkaarlehto",
    "password":"salasana",
    "name": "Juhana Kaarlehto"
}


###
POST localhost:3001/api/login
Content-Type: application/json

{
    "username": "jkaarlehto",
    "password": "salasana"
}


